### ISSUE TITLE
TODO: refine '?makesense_plot()'

### ISSUE THREAD

**Issue by statsccpr** [statsccpr/sensemakr#2]
# TODO: Refine 'makesense_plot.r'
-  (done) Correct Printout of cat() by using CORRECT quantities of magnitude distance to 'net-zero horizon'

- (done) Confirm/Correct linear combination of pretreatment covariate reference line is used correctly
  - right now 'lcpt ref line' is red to highlight/distinguish it from 'net-zero event horizon ref line'
  - iris example shows visual overlap of these two ref lines
    CJH comment:  Let's rename this. "lcpt" unnecessarily cryptic.  How about "combinevars" as the argument for the list of lists.  Can still be lcpt internally, but for the argument name at least.

- (done) Optional: Seperate print() and plot() methods.
  - CJH comment:  plot.makesense method important. 

- Optional: make abs() optional turn on and off supplied by user # or raw
- Optional: summary.makesense method would be good too, summarizing the alpha, gamma, and bias values associated with each coef.

**Comment by statsccpr** [comment]
most implemented, except

Optional: make abs() optional turn on and off supplied by user # or raw

**Comment by mikejacktzen** [comment]
going to close this and make a new 'feature' issue for the two remaining low priority optional tasks
